apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-service
  namespace: mock-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database-service
  template:
    metadata:
      labels:
        app: database-service
    spec:
      containers:
      - name: database-service
        image: 905418033689.dkr.ecr.ap-southeast-1.amazonaws.com/database-service:17f6071
        ports:
        - containerPort: 8081
        envFrom:
        - secretRef:
            name: mongodb-secret
      imagePullSecrets:
      - name: ecr-registry-secret
